package com.danilkinkin.buckwheat.settings

import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Card
import androidx.compose.material3.LinearProgressIndicator
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.livedata.observeAsState
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import com.danilkinkin.buckwheat.LocalWindowInsets
import com.danilkinkin.buckwheat.R
import com.danilkinkin.buckwheat.ai.AiInsightUiState
import com.danilkinkin.buckwheat.ai.AiInsightViewModel
import com.danilkinkin.buckwheat.ai.SpendInsightSummary
import com.danilkinkin.buckwheat.analytics.SpendsCalendar
import com.danilkinkin.buckwheat.analytics.SpendsTrendCard
import com.danilkinkin.buckwheat.analytics.SpendsWeekdayCard
import com.danilkinkin.buckwheat.analytics.VIEWER_HISTORY_SHEET
import com.danilkinkin.buckwheat.analytics.categoriesChart.CategoriesChartCard
import com.danilkinkin.buckwheat.analytics.categoriesChart.SpendCategoriesCard
import com.danilkinkin.buckwheat.base.LocalBottomSheetScrollState
import com.danilkinkin.buckwheat.data.AppViewModel
import com.danilkinkin.buckwheat.data.ExtendCurrency
import com.danilkinkin.buckwheat.data.PathState
import com.danilkinkin.buckwheat.ui.colorBad
import com.danilkinkin.buckwheat.ui.colorGood
import com.danilkinkin.buckwheat.ui.colorNotGood
import com.danilkinkin.buckwheat.util.isZero
import com.danilkinkin.buckwheat.util.numberFormat
import com.danilkinkin.buckwheat.util.prettyDate
import com.danilkinkin.buckwheat.util.toDate
import java.math.BigDecimal
import java.math.RoundingMode

const val AI_INSIGHT_SHEET = "aiInsight"

// Monthly report of the current budget period, reached from Settings. It always works: the
// overview loads instantly from local analytics (budget status + chart images), the narrative is
// generated by the built-in offline engine, and when AI is configured it tries to upgrade that
// narrative in the background (swapping in the AI text on success).
@Composable
fun AiInsightSheet(
    appViewModel: AppViewModel = hiltViewModel(),
    aiInsightViewModel: AiInsightViewModel = hiltViewModel(),
) {
    val localBottomSheetScrollState = LocalBottomSheetScrollState.current
    val state by aiInsightViewModel.state.observeAsState(AiInsightUiState.Idle)
    val currentState = state

    val navigationBarHeight = androidx.compose.ui.unit.max(
        LocalWindowInsets.current.calculateBottomPadding(),
        16.dp,
    )

    LaunchedEffect(Unit) {
        if (aiInsightViewModel.state.value == AiInsightUiState.Idle) {
            aiInsightViewModel.generate()
        }
    }

    Surface(Modifier.padding(top = localBottomSheetScrollState.topPadding)) {
        Column {
            Box(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(24.dp),
                contentAlignment = Alignment.Center
            ) {
                Text(
                    text = stringResource(R.string.ai_insight_title),
                    style = MaterialTheme.typography.titleLarge,
                )
            }
            Column(
                modifier = Modifier
                    .verticalScroll(rememberScrollState())
                    .padding(horizontal = 24.dp)
                    .padding(bottom = navigationBarHeight)
            ) {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Text(
                        text = stringResource(R.string.ai_insight_description),
                        style = MaterialTheme.typography.bodyMedium,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                        modifier = Modifier.weight(1f),
                    )
                    when (currentState) {
                        is AiInsightUiState.Report -> {
                            if (!currentState.aiLoading) {
                                TextButton(onClick = { aiInsightViewModel.generate() }) {
                                    Text(stringResource(R.string.ai_insight_regenerate))
                                }
                            }
                        }
                        is AiInsightUiState.Error ->
                            TextButton(onClick = { aiInsightViewModel.generate() }) {
                                Text(stringResource(R.string.ai_insight_retry))
                            }
                        else -> {}
                    }
                }
                Spacer(Modifier.height(8.dp))
                when (currentState) {
                    AiInsightUiState.Idle, AiInsightUiState.Loading -> {
                        LinearProgressIndicator(modifier = Modifier.fillMaxWidth())
                        Spacer(Modifier.height(8.dp))
                        Text(
                            text = stringResource(R.string.ai_insight_loading),
                            style = MaterialTheme.typography.bodyMedium,
                            color = MaterialTheme.colorScheme.onSurfaceVariant,
                        )
                    }
                    is AiInsightUiState.Error -> {
                        Text(
                            text = currentState.message,
                            style = MaterialTheme.typography.bodyMedium,
                            color = MaterialTheme.colorScheme.error,
                        )
                        Spacer(Modifier.height(8.dp))
                    }
                    is AiInsightUiState.Report -> MonthReportBody(currentState, appViewModel)
                }
            }
        }
    }
}

// The at-a-glance month overview: budget status card, then the analytics chart "images" fed from
// the period data, then the narrative (AI or offline) with a source badge.
@Composable
private fun MonthReportBody(
    report: AiInsightUiState.Report,
    appViewModel: AppViewModel,
) {
    val data = report.data
    Column(Modifier.fillMaxWidth()) {
        ReportStatusCard(data.summary)
        Spacer(Modifier.height(16.dp))
        SpendsTrendCard(
            modifier = Modifier.fillMaxWidth(),
            spends = data.spends,
            startDate = data.startDate,
            finishDate = data.finishDate,
            currency = data.currency,
            periods = data.periods,
        )
        Spacer(Modifier.height(16.dp))
        SpendCategoriesCard(
            modifier = Modifier.fillMaxWidth(),
            spends = data.spends,
            currency = data.currency,
        )
        Spacer(Modifier.height(16.dp))
        CategoriesChartCard(
            modifier = Modifier.fillMaxWidth(),
            spends = data.spends,
            currency = data.currency,
        )
        Spacer(Modifier.height(16.dp))
        SpendsWeekdayCard(
            modifier = Modifier.fillMaxWidth(),
            spends = data.spends,
            startDate = data.startDate,
            finishDate = data.finishDate,
            currency = data.currency,
        )
        Spacer(Modifier.height(16.dp))
        SpendsCalendar(
            modifier = Modifier.fillMaxWidth(),
            budget = data.summary.budget,
            transactions = data.transactions,
            startDate = data.startDate,
            finishDate = data.finishDate,
            currency = data.currency,
            dailyBudget = data.summary.dailyBudget,
            onDayClick = { date ->
                appViewModel.openSheet(
                    PathState(
                        name = VIEWER_HISTORY_SHEET,
                        args = mapOf("onlyDay" to date),
                    )
                )
            },
        )
        Spacer(Modifier.height(16.dp))
        ReportNarrative(report)
    }
}

// Summary state: period range, budget / spent / left, %-used progress bar and on-track status.
@Composable
private fun ReportStatusCard(summary: SpendInsightSummary) {
    val context = LocalContext.current
    val currency = ExtendCurrency.getInstance(summary.currencyCode.takeIf { it.isNotBlank() })
    val budget = summary.budget
    val spent = summary.spent
    val percentUsed = if (budget.isZero()) {
        0
    } else {
        spent.multiply(BigDecimal(100))
            .divide(budget, 0, RoundingMode.HALF_EVEN)
            .toInt()
    }
    val remaining = (budget - spent).coerceAtLeast(BigDecimal.ZERO)
    val overBudget = budget > BigDecimal.ZERO && spent > budget
    val statusColor = when {
        overBudget -> colorBad
        percentUsed >= 80 -> colorNotGood
        else -> colorGood
    }
    val statusText = when {
        overBudget -> stringResource(
            R.string.monthly_report_over_by,
            numberFormat(context, spent - budget, currency),
        )
        percentUsed >= 80 -> stringResource(R.string.monthly_report_used, percentUsed)
        else -> stringResource(R.string.monthly_report_on_track)
    }

    Card(
        modifier = Modifier.fillMaxWidth(),
        shape = MaterialTheme.shapes.extraLarge,
    ) {
        Column(
            Modifier
                .fillMaxWidth()
                .padding(horizontal = 24.dp, vertical = 16.dp)
        ) {
            Row(verticalAlignment = Alignment.CenterVertically) {
                Column(Modifier.weight(1f)) {
                    Text(
                        text = stringResource(R.string.monthly_report_summary),
                        style = MaterialTheme.typography.titleMedium,
                    )
                    Spacer(Modifier.height(4.dp))
                    Text(
                        text = stringResource(
                            R.string.monthly_report_dates,
                            prettyDate(
                                summary.startDate.toDate(),
                                showTime = false,
                                forceShowDate = true,
                                shortMonth = true,
                            ),
                            prettyDate(
                                summary.endDate.toDate(),
                                showTime = false,
                                forceShowDate = true,
                                shortMonth = true,
                            ),
                        ),
                        style = MaterialTheme.typography.labelMedium,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                    )
                }
                Text(
                    text = statusText,
                    style = MaterialTheme.typography.titleMedium,
                    color = statusColor,
                )
            }
            Spacer(Modifier.height(16.dp))
            Row(Modifier.fillMaxWidth()) {
                StatusValue(
                    label = stringResource(R.string.monthly_report_budget),
                    value = numberFormat(context, budget, currency),
                    modifier = Modifier.weight(1f),
                )
                StatusValue(
                    label = stringResource(R.string.monthly_report_spent),
                    value = numberFormat(context, spent, currency),
                    modifier = Modifier.weight(1f),
                )
                StatusValue(
                    label = stringResource(R.string.monthly_report_left),
                    value = numberFormat(context, remaining, currency),
                    modifier = Modifier.weight(1f),
                    alignEnd = true,
                )
            }
            Spacer(Modifier.height(16.dp))
            LinearProgressIndicator(
                progress = {
                    if (budget.isZero()) {
                        0f
                    } else {
                        spent.divide(budget, 4, RoundingMode.HALF_EVEN)
                            .toFloat()
                            .coerceIn(0f, 1f)
                    }
                },
                modifier = Modifier
                    .fillMaxWidth()
                    .height(8.dp),
                color = statusColor,
                trackColor = MaterialTheme.colorScheme.surfaceContainerHigh,
            )
        }
    }
}

@Composable
private fun StatusValue(
    label: String,
    value: String,
    modifier: Modifier = Modifier,
    alignEnd: Boolean = false,
) {
    Column(
        modifier = modifier,
        horizontalAlignment = if (alignEnd) Alignment.End else Alignment.Start,
    ) {
        Text(
            text = label,
            style = MaterialTheme.typography.labelMedium,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
        )
        Spacer(Modifier.height(2.dp))
        Text(
            text = value,
            style = MaterialTheme.typography.titleMedium,
            color = MaterialTheme.colorScheme.onSurface,
        )
    }
}

// The narrative card: an AI/Offline badge, an optional "improving with AI" / AI-failure caption,
// then the report body.
@Composable
private fun ReportNarrative(report: AiInsightUiState.Report) {
    Card(
        modifier = Modifier.fillMaxWidth(),
        shape = MaterialTheme.shapes.extraLarge,
    ) {
        Column(
            Modifier
                .fillMaxWidth()
                .padding(horizontal = 24.dp, vertical = 16.dp)
        ) {
            Row(verticalAlignment = Alignment.CenterVertically) {
                Text(
                    text = stringResource(
                        if (report.isAi) R.string.monthly_report_badge_ai
                        else R.string.monthly_report_badge_offline
                    ),
                    style = MaterialTheme.typography.labelMedium,
                    color = MaterialTheme.colorScheme.primary,
                )
                Spacer(Modifier.weight(1f))
                if (report.aiLoading) {
                    Text(
                        text = stringResource(R.string.monthly_report_ai_loading),
                        style = MaterialTheme.typography.labelMedium,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                    )
                }
            }
            if (!report.isAi && report.aiFailure != null && !report.aiLoading) {
                Spacer(Modifier.height(4.dp))
                Text(
                    text = stringResource(R.string.monthly_report_ai_failed, report.aiFailure),
                    style = MaterialTheme.typography.labelSmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                )
            }
            Spacer(Modifier.height(12.dp))
            ReportBody(report.text)
        }
    }
}

// Renders the report line by line: "• " bullet lines become bullet rows, everything else a
// paragraph. Plain text would read like a wall of text; this keeps the report scannable.
@Composable
private fun ReportBody(text: String) {
    val lines = remember(text) { text.lines() }
    Column(Modifier.fillMaxWidth()) {
        lines.forEach { rawLine ->
            val line = rawLine.trim()
            when {
                line.isEmpty() -> Spacer(Modifier.height(6.dp))
                line.startsWith("•") -> {
                    Row(Modifier.padding(top = 4.dp)) {
                        Text(
                            text = "•",
                            style = MaterialTheme.typography.bodyMedium,
                            fontWeight = FontWeight.Bold,
                            color = MaterialTheme.colorScheme.primary,
                        )
                        Spacer(Modifier.width(8.dp))
                        Text(
                            text = line.removePrefix("•").trim(),
                            style = MaterialTheme.typography.bodyMedium,
                            color = MaterialTheme.colorScheme.onSurface,
                            modifier = Modifier.weight(1f),
                        )
                    }
                }
                else -> Text(
                    text = line,
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.onSurface,
                    modifier = Modifier.padding(top = 4.dp),
                )
            }
        }
    }
}
